"""Initial migration

Revision ID: 31fd0cf0c332
Revises: 
Create Date: 2025-04-01 21:38:41.684274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fd0cf0c332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(), nullable=True))
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
